[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
categories = []
description = "TODO"
documentation = "https://docs.rs/total-order-multi-map"
keywords = ["map", "vec", "ordered"]
license = "MIT OR Apache-2.0"
name = "total-order-multi-map"
readme = "./README.md"
repository = "https://github.com/1aim/mail-codec/"
version = "0.1.0"

[dependencies]
stable_deref_trait = "1.0"
